---
title: "R Notebook"
output: html_notebook
---


```{r}
load("ThreeCancers.RData")
install.packages('ggplot2')
y = as.numeric(CancerType == 'KIRC')
```

```{r}
# Question 3i 
set.seed(10)
# explanatory variable 
x <- seq(0,3, length.out = 30)
#noise 
noise <- rnorm(n= 30, mean= 0, sd = .1)
#observed data
y <- 3 + .5*x + noise
# make dataframe 
df <- data.frame(list(explanatory= x, observed_val = y))

# plot observed data plus true data generating function
plot(x = x, y= y)
lines(x = x, y = 3 + .5*x)

fit <- lm(formula = observed_val ~ explanatory, data = df)
summary(fit) 

# Question 3ii
#a) The estimated coefficant is 0.48226 
#b) the p value associated with the coefficiant for Gene15 is  < 2.2e-16
#c) The p-values for the null hypotheis that the corresponding coefficient is zero.
#d) we can conclude that the coefficients you get estimates the standard errors, t-values and p-values

#Question 3iii
# the following code gives us the linear function
#β0 is the unknown intercept which is 5
#β1 the unknown slope  which is 2
x = seq(0, 10, by = 0.5)
beta0 = 5
beta1 = 2
y = beta0 + beta1 * x 
plot(x, y)
lines(x, y, col='blue')
```


